DROP TABLE PMSFILE; -- 프로젝트 테이블 삭제
DROP SEQUENCE PMSFILE_NO_SEQ; -- 시퀀스 삭제
-- ALTER TABLE PR_PROJECT RENAME COLUMN 기존컬럼명 to 변경컬럼; -- 컬럼명 수정


CREATE TABLE PMSFILE (
   FILE_NO NUMBER CONSTRAINT PK_FILE_NO PRIMARY KEY, -- 첨부파일 번호
   BOARD_NO NUMBER, -- 게시글 번호
   CONSTRAINT FK_PMSFILE_BOARD_NO FOREIGN KEY(BOARD_NO)
   REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE, 
   RISK_NO NUMBER, -- 리스크 번호
   CONSTRAINT FK_PMSFILE_RISK_NO FOREIGN KEY(RISK_NO)
   REFERENCES RISK(RISK_NO) ON DELETE CASCADE,
   FNAME VARCHAR(100), -- 파일명
   PATHNAME VARCHAR(500), -- 파일경로
   CREDTE DATE -- 업로드일
);
   
-- PMSFILE_NO 시퀀스 생성
create sequence PMSFILE_NO_SEQ start with 1
minvalue 1 maxvalue 1000000 CYCLE; 

SELECT * FROM PMSFILE;

INSERT INTO PMSFILE VALUES(PMSFILE_NO_SEQ.NEXTVAL, 1, '', 'PMS 요구사항 정의서', '경로', '2021-03-25');
INSERT INTO PMSFILE VALUES(PMSFILE_NO_SEQ.NEXTVAL, 2, '', 'PMS일정계획 보고서', '경로', '2021-03-26');
INSERT INTO PMSFILE VALUES(PMSFILE_NO_SEQ.NEXTVAL, 10, '', 'PMS공통모듈 구현 list', '경로', '2021-04-01');
INSERT INTO PMSFILE VALUES(PMSFILE_NO_SEQ.NEXTVAL, 13, '', 'PMS check sheet', '경로', '2021-04-26');

INSERT INTO PMSFILE VALUES(PMSFILE_NO_SEQ.NEXTVAL, '', 1, '참여인원 개발', '경로', '2021-03-30');
INSERT INTO PMSFILE VALUES(PMSFILE_NO_SEQ.NEXTVAL, '', 3, '비용절감 보고서', '경로', '2021-03-30');
INSERT INTO PMSFILE VALUES(PMSFILE_NO_SEQ.NEXTVAL, '', 6, '인원충원 risk 보고서', '경로', '2021-04-20');
INSERT INTO PMSFILE VALUES(PMSFILE_NO_SEQ.NEXTVAL, '', 9, '특정패턴 오류 보고서', '경로', '2021-03-30');







