DROP TABLE PR_PROJECT; -- 프로젝트 테이블 삭제
DROP SEQUENCE PR_PROJECT_NO_SEQ; -- 시퀀스 삭제
-- ALTER TABLE PR_PROJECT RENAME COLUMN 기존컬럼명 to 변경컬럼; -- 컬럼명 수정


CREATE TABLE PR_PROJECT(
	PR_NO NUMBER CONSTRAINT PK_PR_NO PRIMARY KEY, -- 프로젝트 번호
	PR_TITLE VARCHAR(200), -- 프로젝트 명
	PR_DATE DATE, -- 프로젝트 등록 날짜
	PR_SDATE VARCHAR(50), -- 프로젝트 시작 일자
	PR_EDATE VARCHAR(50), -- 프로젝트 종료 일자
	PR_STATE VARCHAR(50), -- 상태(진행전, 진행중, 완료)
	MEM_NO NUMBER, -- 사원번호(PM)
	CONSTRAINT FK_PR_PROJECT_MEM_NO FOREIGN KEY (MEM_NO)
	REFERENCES MEMBERS(MEM_NO) ON DELETE SET NULL
);

CREATE SEQUENCE PR_PROJECT_NO_SEQ START WITH 1
MINVALUE 1 MAXVALUE 1000000 CYCLE;

SELECT * FROM PR_PROJECT;

-- 특정 프로젝트 조회
SELECT pp.*, m.MEM_NAME 
FROM PR_PROJECT pp ,MEMBERS m 
WHERE pp.MEM_NO = m.MEM_NO AND PR_NO =1;

SELECT pp.*, m.MEM_NAME 
FROM PR_PROJECT pp ,MEMBERS m 
WHERE pp.MEM_NO = m.MEM_NO AND m.MEM_NO = 1000;

-- 등록
INSERT INTO PR_PROJECT VALUES(PR_PROJECT_NO_SEQ.NEXTVAL, 'PMS 프로젝트', '2021-03-18', '2021-03-22', '2021-04-30', '진행중', 1000);

INSERT INTO PR_PROJECT VALUES(PR_PROJECT_NO_SEQ.NEXTVAL, '미니홈피 프로젝트', '2021-03-20', '2021-03-26', '2021-04-25', '진행중', 1005);

INSERT INTO PR_PROJECT VALUES(PR_PROJECT_NO_SEQ.NEXTVAL, 'A쇼핑몰 프로젝트', '2021-03-20', '2021-03-26', '2021-05-25', '진행전', 1020);
INSERT INTO PR_PROJECT VALUES(PR_PROJECT_NO_SEQ.NEXTVAL, 'test', sysdate, '2021-03-30', '2021-05-30', '진행전', 1020);



-- 특정 프로젝트 조회
SELECT pp.*, m.MEM_NAME 
FROM PR_PROJECT pp, MEMBERS m 
WHERE pp.MEM_NO = m.MEM_NO AND PR_NO = 1;

-- 수정
UPDATE PR_PROJECT
	SET PR_TITLE = '게임 프로젝트',
		PR_SDATE = '2021-03-25',
		PR_EDATE = '2021-05-25',
		PR_STATE = '진행완료' -- 진행전, 진행중, 진행완료 수정 처리
	WHERE PR_NO = 1 AND MEM_NO = 1000;
-- 원본
UPDATE PR_PROJECT
	SET PR_TITLE = 'PMS 프로젝트',
		PR_SDATE = '2021-03-22',
		PR_EDATE = '2021-04-30',
		PR_STATE = '진행중'
	WHERE PR_NO = 1 AND MEM_NO = 1000;
-- 삭제
DELETE FROM PR_PROJECT
WHERE PR_NO = 23; -- 해당 프로젝트에 저장된 업무도 모두 삭제 처리

-- ### 대시보드
-- 프로젝트 별 계획 일정 진행도 조회
SELECT PR_TITLE, m.MEM_NAME , PR_SDATE, PR_EDATE, d.DNAME, 
	FLOOR(((SYSDATE - TO_DATE(PR_SDATE)) 
	/ (TO_DATE(PR_EDATE) - TO_DATE(PR_SDATE))) *100) || '%' prog -- 계획 대 진행도 (날자 기준)
FROM PR_PROJECT p, MEMBERS m, DEPT d
WHERE p.MEM_NO = m.MEM_NO AND m.DEPTNO = d.DEPTNO AND PR_STATE = '진행중';
-- 오늘까지 프로젝트 실제 진행도 조회
SELECT avg(TS_RATE) || '%' rprog
FROM PR_TASK
WHERE TS_NO IN(1, 6, 10, 12)
GROUP BY PR_NO;
SELECT avg(TS_RATE) || '%' prog
FROM PR_TASK
WHERE TS_NO IN(1, 6, 10, 12)
GROUP BY PR_NO;


SELECT PR_TITLE, m.MEM_NAME , PR_SDATE, PR_EDATE, d.DNAME, 
	(TO_DATE(PR_EDATE) - TO_DATE(PR_SDATE))-- sysdate 프로젝트 시작날 
FROM PR_PROJECT p, MEMBERS m, DEPT d
WHERE p.MEM_NO = m.MEM_NO AND m.DEPTNO = d.DEPTNO AND PR_STATE = '진행중' AND PR_EDATE < SYSDATE ;


SELECT avg(TS_RATE)
FROM PR_TASK
WHERE TS_REFNO = 0 
GROUP BY PR_NO;

-- RISK 항목 별 진행 중 개수 조회
SELECT RISK_LIST, COUNT(RISK_LIST)
FROM RISK
WHERE RISK_STATE = '조치중'
GROUP BY RISK_LIST;

-- 전체 사원인원 조회
SELECT COUNT(MEM_NO) AS "총 인원"
FROM MEMBERS;
-- 프로젝트 참워인원 조회
SELECT count(MEM_NO) AS "프로젝트 참여 인원"
FROM MEMBERS
WHERE mem_state ='투입중';
-- 프로젝트 미참여 인원
SELECT count(MEM_NO) AS "프로젝트 미참여 인원"
FROM MEMBERS
WHERE mem_state ='투입전';

SELECT *
FROM MEMBERS
WHERE AUTH = 'pm';

SELECT * FROM PR_PROJECT
WHERE PR_NO = 1;

	SELECT PR_TITLE, PR_NO, PR_SDATE, PR_EDATE, 100 AS prog_tot, ROUND((SYSDATE - TO_DATE(PR_SDATE))/(TO_DATE(PR_EDATE)-TO_DATE(PR_SDATE))*100,0) AS prog 
	FROM PR_PROJECT
	WHERE PR_STATE = '진행중' AND PR_EDATE > SYSDATE;
